name: Continous Integration
on: [push, pull_request]
env:
  CARGO_TERM_COLOR: always
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
        features: ['', '--features std']
    steps:
      - uses: actions/checkout@v2
      - name: Check Syntax
        run: cargo clippy ${{ matrix.features }} --all-targets -vv
      - name: Run Tests
        run: cargo test ${{ matrix.features }} -vv
      - name: Build Documentation
        run: cargo doc ${{ matrix.features }} --no-deps -vv
      - name: Check Formatting
        run: cargo fmt -v -- --check
